<?php

namespace App\Services\TextureSuggestions\Providers;

use App\Services\TextureSuggestions\Contracts\TextureSuggestionProvider;
use Illuminate\Http\Client\Factory as HttpFactory;
use Illuminate\Http\Client\RequestException;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use RuntimeException;
use Throwable;

class GeminiTextureSuggestionProvider implements TextureSuggestionProvider
{
    public function __construct(
        protected HttpFactory $http
    ) {
    }

    public function generate(array $context, int $count, ?array $screenshot = null): array
    {
        $config = config('texture_suggestions.gemini');
        $apiKey = (string) ($config['api_key'] ?? '');
        $model = (string) ($config['model'] ?? 'gemini-3.1-flash-image-preview');
        $endpoint = rtrim((string) ($config['endpoint'] ?? 'https://generativelanguage.googleapis.com/v1beta/models'), '/');

        if ($apiKey === '') {
            throw new RuntimeException('Gemini API key belum diatur. Isi GEMINI_API_KEY untuk mengaktifkan generate texture AI.');
        }

        $assets = [];
        $errors = [];

        for ($index = 1; $index <= $count; $index++) {
            try {
                [$parts, $imagePart] = $this->requestImageParts(
                    apiKey: $apiKey,
                    endpoint: $endpoint,
                    model: $model,
                    context: $context,
                    index: $index,
                    count: $count,
                    screenshot: $screenshot,
                );
            } catch (RuntimeException $exception) {
                $errors[] = 'Variation '.$index.': '.$exception->getMessage();
                continue;
            }

            $imageBase64 = data_get($imagePart, 'inlineData.data')
                ?: data_get($imagePart, 'inline_data.data');
            $mimeType = data_get($imagePart, 'inlineData.mimeType')
                ?: data_get($imagePart, 'inline_data.mime_type')
                ?: data_get($imagePart, 'inline_data.mimeType')
                ?: data_get($imagePart, 'inlineData.mime_type')
                ?: 'image/png';

            if (! is_string($imageBase64) || trim($imageBase64) === '') {
                throw new RuntimeException('Gemini mengembalikan image kosong.');
            }

            $binary = base64_decode($imageBase64, true);

            if ($binary === false) {
                throw new RuntimeException('Image hasil Gemini tidak bisa didekode dari base64.');
            }

            $assets[] = [
                'name' => $this->assetName($context, $index),
                'label' => 'Variation '.$index,
                'mime_type' => $mimeType,
                'binary' => $binary,
                'reason' => $this->extractTextSummary($parts) ?: 'Generated by Gemini from the selected part context.',
            ];
        }

        if ($assets === []) {
            throw new RuntimeException($this->formatGenerationFailureMessage($errors));
        }

        return $assets;
    }

    /**
     * @param  array<string, mixed>  $context
     * @param  array<string, mixed>|null  $screenshot
     * @return array{0: array<int, array<string, mixed>>, 1: array<string, mixed>}
     */
    protected function requestImageParts(
        string $apiKey,
        string $endpoint,
        string $model,
        array $context,
        int $index,
        int $count,
        ?array $screenshot = null
    ): array {
        $attemptMessages = [];

        foreach ($this->buildPayloadVariants($context, $index, $count, $screenshot) as $attempt => $payload) {
            try {
                $response = $this->http
                    ->connectTimeout((int) config('texture_suggestions.connect_timeout', 20))
                    ->timeout((int) config('texture_suggestions.timeout', 30))
                    ->withHeaders([
                        'x-goog-api-key' => $apiKey,
                        'Content-Type' => 'application/json',
                    ])
                    ->post("{$endpoint}/{$model}:generateContent", $payload)
                    ->throw();
            } catch (RequestException $exception) {
                $message = Arr::get($exception->response?->json(), 'error.message')
                    ?: $exception->getMessage();

                throw new RuntimeException('Gemini image generation gagal: '.$message, previous: $exception);
            } catch (Throwable $exception) {
                throw new RuntimeException('Gemini image generation gagal: '.$exception->getMessage(), previous: $exception);
            }

            $responseJson = $response->json();
            $parts = data_get($responseJson, 'candidates.0.content.parts', []);
            $imagePart = $this->extractImagePart($parts);

            if (is_array($imagePart)) {
                return [$parts, $imagePart];
            }

            $finishReason = (string) data_get($responseJson, 'candidates.0.finishReason', 'UNKNOWN');
            $finishMessage = trim((string) data_get($responseJson, 'candidates.0.finishMessage', ''));
            $attemptMessages[] = sprintf(
                'Attempt %d: %s%s',
                $attempt + 1,
                $finishReason,
                $finishMessage !== '' ? ' - '.$finishMessage : ''
            );
        }

        throw new RuntimeException(
            'Gemini tidak mengembalikan image texture yang bisa disimpan. '
            .$this->formatAttemptMessages($attemptMessages)
        );
    }

    /**
     * @param  array<string, mixed>  $context
     * @param  array<string, mixed>|null  $screenshot
     * @return array<int, array<string, mixed>>
     */
    protected function buildPromptParts(array $context, int $index, int $count, ?array $screenshot = null): array
    {
        $parts = [];

        if ($screenshot) {
            $parts[] = [
                'inline_data' => [
                    'mime_type' => $screenshot['mime_type'],
                    'data' => $screenshot['base64'],
                ],
            ];
        }

        $parts[] = [
            'text' => $this->buildPrimaryPrompt($context, $index, $count),
        ];

        return $parts;
    }

    /**
     * @param  array<int, array<string, mixed>>  $parts
     * @return array<string, mixed>|null
     */
    protected function extractImagePart(array $parts): ?array
    {
        $imagePart = collect($parts)->first(function (array $part) {
            return isset($part['inlineData']['data']) || isset($part['inline_data']['data']);
        });

        return is_array($imagePart) ? $imagePart : null;
    }

    /**
     * @param  array<int, array<string, mixed>>  $parts
     */
    protected function extractTextSummary(array $parts): ?string
    {
        $text = collect($parts)
            ->pluck('text')
            ->filter(fn ($value) => is_string($value) && trim($value) !== '')
            ->implode(' ');

        return $text !== '' ? trim($text) : null;
    }

    /**
     * @param  array<string, mixed>  $context
     */
    protected function buildPrimaryPrompt(array $context, int $index, int $count): string
    {
        $userPrompt = $this->cleanPromptValue(
            $context['user_prompt'] ?? '',
            'Create a suitable material texture for the selected model part.'
        );
        [$styleLabel, $styleDirection] = $this->resolveStyleDirection($context);
        $partName = $this->cleanPromptValue($context['selected_part_name'] ?? '', 'Selected part');
        $meshName = $this->cleanPromptValue($context['selected_mesh_name'] ?? '', 'unknown mesh');
        $modelName = $this->cleanPromptValue($context['model_name'] ?? '', '3D model');
        $modelDescription = $this->cleanPromptValue($context['model_description'] ?? '', 'No description');

        $segments = [
            'Generate one new square seamless texture tile for a 3D model material.',
            "Selected part: {$partName} (mesh: {$meshName}) on model \"{$modelName}\".",
            "Model context: {$modelDescription}.",
            "User prompt, highest priority: \"{$userPrompt}\".",
            "Selected style: {$styleLabel}. {$styleDirection}.",
            'Follow the user prompt literally, including requested material, color, pattern, mood, and finish.',
            'Understand Indonesian and English material/color words directly, for example merah means red and beludru means velvet.',
            'If a reference screenshot is attached, use it only to understand the selected part and model scale; ignore existing colors, existing materials, and blue selection highlights.',
            'Output a flat tileable material swatch only, suitable for UV texture mapping.',
            'Do not include a garment, person, mannequin, body, scene, product photo, logo, watermark, text, border, or UI.',
            $this->shortVariationInstruction($index, $count),
        ];

        $motif = $this->resolveMotifDirection($context);

        if ($motif) {
            $segments[] = "Include {$motif}.";
        }

        return implode(' ', $segments);
    }

    protected function shortVariationInstruction(int $index, int $count): string
    {
        $hints = [
            1 => 'Keep it balanced and versatile.',
            2 => 'Make this variation slightly richer in micro detail.',
            3 => 'Make this variation cleaner and more refined.',
            4 => 'Make this variation a bit bolder while still usable.',
        ];

        return $hints[$index] ?? "Create variation {$index} of {$count} with a distinct but related finish.";
    }

    /**
     * @param  array<string, mixed>  $context
     */
    protected function resolveColorDirection(array $context): string
    {
        $haystack = strtolower(implode(' ', array_filter([
            (string) ($context['style'] ?? ''),
            (string) ($context['user_prompt'] ?? ''),
        ])));

        $colors = [
            'merah muda',
            'abu-abu',
            'abu abu',
            'navy',
            'black',
            'white',
            'blue',
            'red',
            'green',
            'yellow',
            'orange',
            'purple',
            'pink',
            'brown',
            'beige',
            'cream',
            'gold',
            'silver',
            'gray',
            'grey',
            'hitam',
            'putih',
            'biru',
            'merah',
            'hijau',
            'kuning',
            'jingga',
            'oranye',
            'ungu',
            'coklat',
            'cokelat',
            'emas',
            'perak',
        ];

        foreach ($colors as $color) {
            if (str_contains($haystack, $color)) {
                return $this->normalizeColorDirection($color);
            }
        }

        return 'the color palette requested by the user';
    }

    /**
     * @param  array<string, mixed>  $context
     */
    protected function resolveSurfaceDirection(array $context): string
    {
        $haystack = strtolower(implode(' ', array_filter([
            (string) ($context['selected_part_name'] ?? ''),
            (string) ($context['style'] ?? ''),
            (string) ($context['user_prompt'] ?? ''),
        ])));

        $map = [
            'knit' => 'knit weave with subtle rib detail',
            'woven' => 'woven textile detail',
            'linen' => 'linen weave texture',
            'cotton' => 'cotton weave texture',
            'denim' => 'denim textile texture',
            'leather' => 'leather grain texture',
            'suede' => 'suede surface texture',
            'silk' => 'silky textile sheen',
            'velvet' => 'velvet fabric texture with soft pile and directional sheen',
            'beludru' => 'velvet fabric texture with soft pile and directional sheen',
            'kain' => 'fabric material texture',
            'wol' => 'wool textile texture',
            'rajut' => 'knit weave with subtle rib detail',
            'tenun' => 'woven textile detail',
            'katun' => 'cotton weave texture',
            'kulit' => 'leather grain texture',
            'sutra' => 'silky textile sheen',
            'kanvas' => 'canvas fabric texture',
        ];

        foreach ($map as $needle => $surface) {
            if (str_contains($haystack, $needle)) {
                return $surface;
            }
        }

        return 'the material surface requested by the user';
    }

    /**
     * @param  array<string, mixed>  $context
     * @return array<int, string>
     */
    protected function stableFallbackPrompts(array $context, int $index, int $count): array
    {
        $userPrompt = $this->cleanPromptValue(
            $context['user_prompt'] ?? '',
            'Create a suitable material texture for the selected part.'
        );
        [$styleLabel, $styleDirection] = $this->resolveStyleDirection($context);
        $partName = $this->cleanPromptValue($context['selected_part_name'] ?? '', 'selected model part');
        $color = $this->resolveColorDirection($context);
        $surface = $this->resolveSurfaceDirection($context);
        $motif = $this->resolveMotifDirection($context);

        $motifPrompt = $motif ? " Include {$motif}." : '';

        return [
            "Create a square seamless texture tile for {$partName}. User request: \"{$userPrompt}\". Style: {$styleLabel}. {$styleDirection}. Match the requested material and color exactly.{$motifPrompt} Flat texture swatch only.",
            "Create an original tileable {$surface} in {$color}. User request: \"{$userPrompt}\". No garment, no person, no text.",
            "Generate a flat seamless material swatch that follows this instruction exactly: \"{$userPrompt}\". Variation {$index} of {$count}.",
        ];
    }

    protected function cleanPromptValue(mixed $value, string $fallback = ''): string
    {
        $text = trim((string) $value);

        if ($text === '') {
            return $fallback;
        }

        $text = (string) preg_replace('/\s+/', ' ', $text);

        return Str::limit($text, 700, '');
    }

    /**
     * @param  array<string, mixed>  $context
     * @return array{0: string, 1: string}
     */
    protected function resolveStyleDirection(array $context): array
    {
        $style = Str::lower(trim((string) ($context['style'] ?? 'auto')));

        return match ($style) {
            'realistic' => [
                'Realistic',
                'Make it physically plausible, like a close material scan with natural lighting and believable surface detail.',
            ],
            'sport', 'sporty' => [
                'Sporty',
                'Make it clean, performance-oriented, durable, energetic, and suitable for modern sportswear.',
            ],
            'luxury' => [
                'Luxury',
                'Make it premium, refined, elegant, and rich in subtle high-end detail without logos.',
            ],
            'natural' => [
                'Natural',
                'Make it organic, tactile, and grounded with natural fiber or material character.',
            ],
            'playful' => [
                'Playful',
                'Make it expressive, lively, and friendly while still usable as a repeated texture.',
            ],
            'minimal' => [
                'Minimal',
                'Make it simple, clean, restrained, and low-noise while preserving the requested material and color.',
            ],
            default => [
                'Auto Detect',
                'Infer the best visual treatment from the user prompt, selected part, and requested material.',
            ],
        };
    }

    protected function normalizeColorDirection(string $color): string
    {
        return match ($color) {
            'grey', 'abu-abu', 'abu abu' => 'gray',
            'hitam' => 'black',
            'putih' => 'white',
            'biru' => 'blue',
            'merah' => 'red',
            'hijau' => 'green',
            'kuning' => 'yellow',
            'jingga', 'oranye' => 'orange',
            'ungu' => 'purple',
            'merah muda' => 'pink',
            'coklat', 'cokelat' => 'brown',
            'emas' => 'gold',
            'perak' => 'silver',
            default => $color,
        };
    }

    /**
     * @param  array<string, mixed>  $context
     */
    protected function resolveMotifDirection(array $context): ?string
    {
        $haystack = Str::lower(implode(' ', array_filter([
            (string) ($context['style'] ?? ''),
            (string) ($context['user_prompt'] ?? ''),
        ])));

        $motifs = [
            'mega mendung' => 'mega mendung-inspired cloud motifs with a generic handcrafted feel',
            'parang' => 'parang-inspired diagonal batik motifs with a generic handcrafted feel',
            'batik' => 'batik-inspired wax-resist motifs with floral and geometric rhythm',
            'ikat' => 'ikat-inspired woven motifs with a handcrafted textile rhythm',
            'songket' => 'songket-inspired ornamental woven motifs in a generic style',
            'floral' => 'subtle floral motifs',
            'geometric' => 'clean geometric motifs',
            'stripe' => 'subtle stripe motifs',
            'stripes' => 'subtle stripe motifs',
            'plaid' => 'soft plaid motifs',
            'checkered' => 'clean checkered motifs',
            'camo' => 'abstract camouflage motifs',
            'camouflage' => 'abstract camouflage motifs',
            'polka' => 'small polka-dot motifs',
        ];

        foreach ($motifs as $needle => $description) {
            if (str_contains($haystack, $needle)) {
                return $description;
            }
        }

        return null;
    }

    /**
     * @param  array<int, array<string, mixed>>  $context
     * @param  array<string, mixed>|null  $screenshot
     * @return array<int, array<string, mixed>>
     */
    protected function buildPayloadVariants(array $context, int $index, int $count, ?array $screenshot = null): array
    {
        $basePromptParts = $this->buildPromptParts($context, $index, $count, $screenshot);
        $payloads = [
            [
                'contents' => [[
                    'parts' => $basePromptParts,
                ]],
                'generationConfig' => [
                    'responseModalities' => ['TEXT', 'IMAGE'],
                ],
            ],
        ];

        if ($screenshot) {
            $payloads[] = [
                'contents' => [[
                    'parts' => $this->buildPromptParts($context, $index, $count, null),
                ]],
                'generationConfig' => [
                    'responseModalities' => ['TEXT', 'IMAGE'],
                ],
            ];
        }

        foreach ($this->stableFallbackPrompts($context, $index, $count) as $prompt) {
            $payloads[] = [
                'contents' => [[
                    'parts' => [[
                        'text' => $prompt,
                    ]],
                ]],
                'generationConfig' => [
                    'responseModalities' => ['TEXT', 'IMAGE'],
                ],
            ];
        }

        return $payloads;
    }

    /**
     * @param  array<int, string>  $attemptMessages
     */
    protected function formatAttemptMessages(array $attemptMessages): string
    {
        return implode(' | ', array_filter($attemptMessages));
    }

    /**
     * @param  array<int, string>  $errors
     */
    protected function formatGenerationFailureMessage(array $errors): string
    {
        if ($errors === []) {
            return 'Gemini tidak mengembalikan image texture yang bisa disimpan.';
        }

        return 'Gemini tidak mengembalikan image texture yang bisa disimpan. '.implode(' | ', $errors);
    }

    /**
     * @param  array<string, mixed>  $context
     */
    protected function assetName(array $context, int $index): string
    {
        $partName = trim((string) ($context['selected_part_name'] ?? 'Part'));
        $style = trim((string) ($context['style'] ?? 'ai'));

        return "AI {$partName} {$style} Texture {$index}";
    }
}
