<?php

namespace App\Services\TextureSuggestions\Providers;

use Illuminate\Http\Client\RequestException;
use Illuminate\Support\Arr;
use RuntimeException;
use Throwable;

class OpenRouterTextureSuggestionProvider extends GeminiTextureSuggestionProvider
{
    public function generate(array $context, int $count, ?array $screenshot = null): array
    {
        $config = config('texture_suggestions.openrouter');
        $apiKey = (string) ($config['api_key'] ?? '');
        $model = (string) ($config['model'] ?? 'google/gemini-2.5-flash-image');
        $endpoint = rtrim((string) ($config['endpoint'] ?? 'https://openrouter.ai/api/v1'), '/');

        if ($apiKey === '') {
            throw new RuntimeException('OpenRouter API key belum diatur. Isi OPENROUTER_API_KEY untuk mengaktifkan generate texture AI.');
        }

        $assets = [];
        $errors = [];

        for ($index = 1; $index <= $count; $index++) {
            try {
                [$message, $imageUrl] = $this->requestImageMessage(
                    apiKey: $apiKey,
                    endpoint: $endpoint,
                    model: $model,
                    context: $context,
                    index: $index,
                    count: $count,
                    screenshot: $screenshot,
                );
            } catch (RuntimeException $exception) {
                $errors[] = 'Variation '.$index.': '.$exception->getMessage();
                continue;
            }

            [$mimeType, $imageBase64] = $this->parseDataUrl($imageUrl);
            $binary = base64_decode($imageBase64, true);

            if ($binary === false) {
                throw new RuntimeException('Image hasil OpenRouter tidak bisa didekode dari base64.');
            }

            $assets[] = [
                'name' => $this->assetName($context, $index),
                'label' => 'Variation '.$index,
                'mime_type' => $mimeType,
                'binary' => $binary,
                'reason' => $this->extractMessageSummary($message) ?: 'Generated by OpenRouter from the selected part context.',
            ];
        }

        if ($assets === []) {
            throw new RuntimeException($this->formatOpenRouterGenerationFailureMessage($errors));
        }

        return $assets;
    }

    /**
     * @param  array<string, mixed>  $context
     * @param  array<string, mixed>|null  $screenshot
     * @return array{0: array<string, mixed>, 1: string}
     */
    protected function requestImageMessage(
        string $apiKey,
        string $endpoint,
        string $model,
        array $context,
        int $index,
        int $count,
        ?array $screenshot = null
    ): array {
        $attemptMessages = [];

        foreach ($this->buildOpenRouterPayloadVariants($model, $context, $index, $count, $screenshot) as $attempt => $payload) {
            try {
                $response = $this->http
                    ->connectTimeout((int) config('texture_suggestions.connect_timeout', 20))
                    ->timeout((int) config('texture_suggestions.timeout', 30))
                    ->withHeaders($this->headers($apiKey))
                    ->post("{$endpoint}/chat/completions", $payload)
                    ->throw();
            } catch (RequestException $exception) {
                $message = Arr::get($exception->response?->json(), 'error.message')
                    ?: $exception->getMessage();

                throw new RuntimeException('OpenRouter image generation gagal: '.$message, previous: $exception);
            } catch (Throwable $exception) {
                throw new RuntimeException('OpenRouter image generation gagal: '.$exception->getMessage(), previous: $exception);
            }

            $responseJson = $response->json();
            $message = data_get($responseJson, 'choices.0.message', []);
            $imageUrl = $this->extractImageUrl($message);

            if (is_string($imageUrl) && $imageUrl !== '') {
                return [$message, $imageUrl];
            }

            $finishReason = (string) data_get($responseJson, 'choices.0.finish_reason', 'UNKNOWN');
            $attemptMessages[] = sprintf('Attempt %d: %s', $attempt + 1, $finishReason);
        }

        throw new RuntimeException(
            'OpenRouter tidak mengembalikan image texture yang bisa disimpan. '
            .$this->formatAttemptMessages($attemptMessages)
        );
    }

    /**
     * @param  array<string, mixed>  $context
     * @param  array<string, mixed>|null  $screenshot
     * @return array<int, array<string, mixed>>
     */
    protected function buildOpenRouterPayloadVariants(
        string $model,
        array $context,
        int $index,
        int $count,
        ?array $screenshot = null
    ): array {
        $payloads = [
            $this->payload($model, $this->buildMessageContent($this->buildPrimaryPrompt($context, $index, $count), $screenshot)),
        ];

        if ($screenshot) {
            $payloads[] = $this->payload($model, $this->buildMessageContent($this->buildPrimaryPrompt($context, $index, $count), null));
        }

        foreach ($this->stableFallbackPrompts($context, $index, $count) as $prompt) {
            $payloads[] = $this->payload($model, $this->buildMessageContent($prompt, null));
        }

        return $payloads;
    }

    /**
     * @param  array<string, string>|null  $screenshot
     * @return string|array<int, array<string, mixed>>
     */
    protected function buildMessageContent(string $prompt, ?array $screenshot = null): string|array
    {
        if (! $screenshot) {
            return $prompt;
        }

        return [
            [
                'type' => 'text',
                'text' => $prompt,
            ],
            [
                'type' => 'image_url',
                'image_url' => [
                    'url' => sprintf('data:%s;base64,%s', $screenshot['mime_type'], $screenshot['base64']),
                ],
            ],
        ];
    }

    /**
     * @param  string|array<int, array<string, mixed>>  $content
     * @return array<string, mixed>
     */
    protected function payload(string $model, string|array $content): array
    {
        return [
            'model' => $model,
            'messages' => [[
                'role' => 'user',
                'content' => $content,
            ]],
            'modalities' => ['image', 'text'],
            'stream' => false,
            'image_config' => [
                'aspect_ratio' => '1:1',
            ],
        ];
    }

    /**
     * @return array<string, string>
     */
    protected function headers(string $apiKey): array
    {
        $headers = [
            'Authorization' => 'Bearer '.$apiKey,
            'Content-Type' => 'application/json',
        ];

        $siteUrl = trim((string) config('texture_suggestions.openrouter.site_url', ''));
        $appName = trim((string) config('texture_suggestions.openrouter.app_name', ''));

        if ($siteUrl !== '') {
            $headers['HTTP-Referer'] = $siteUrl;
        }

        if ($appName !== '') {
            $headers['X-Title'] = $appName;
        }

        return $headers;
    }

    /**
     * @param  array<string, mixed>  $message
     */
    protected function extractImageUrl(array $message): ?string
    {
        $images = data_get($message, 'images', []);

        if (is_array($images)) {
            foreach ($images as $image) {
                $url = data_get($image, 'image_url.url')
                    ?: data_get($image, 'imageUrl.url')
                    ?: data_get($image, 'url');

                if (is_string($url) && $url !== '') {
                    return $url;
                }
            }
        }

        return null;
    }

    /**
     * @return array{0: string, 1: string}
     */
    protected function parseDataUrl(string $dataUrl): array
    {
        if (! preg_match('/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/', $dataUrl, $matches)) {
            throw new RuntimeException('OpenRouter mengembalikan format image yang tidak didukung.');
        }

        return [$matches[1], $matches[2]];
    }

    /**
     * @param  array<string, mixed>  $message
     */
    protected function extractMessageSummary(array $message): ?string
    {
        $content = $message['content'] ?? null;

        if (is_string($content) && trim($content) !== '') {
            return trim($content);
        }

        if (! is_array($content)) {
            return null;
        }

        $text = collect($content)
            ->pluck('text')
            ->filter(fn ($value) => is_string($value) && trim($value) !== '')
            ->implode(' ');

        return $text !== '' ? trim($text) : null;
    }

    /**
     * @param  array<int, string>  $errors
     */
    protected function formatOpenRouterGenerationFailureMessage(array $errors): string
    {
        if ($errors === []) {
            return 'OpenRouter tidak mengembalikan image texture yang bisa disimpan.';
        }

        return 'OpenRouter tidak mengembalikan image texture yang bisa disimpan. '.implode(' | ', $errors);
    }
}
